name: Deploy docs

on:
  push:
    branches:
      - main
  pull_request:
  repository_dispatch:
    types: [run_build]

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          apk update
          apk add rsync 
      - name: Build Docs
        run: |
          asciidoctor docs/index.adoc
          find . -name .adoc -exec rm -rf '{}' \;
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        if: contains(github.ref,'refs/heads/main')
        with:
          branch: gh-pages
          folder: docs
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}